/**
 * TRIP GENIE - COMPREHENSIVE MOCK DATASET
 * Contains rich datasets for all super-app modules
 */

const TRIP_GENIE_DATA = {
  // 1. Popular Destinations
  destinations: [
    {
      id: 'dest-goa',
      name: 'Goa',
      category: 'Beaches',
      rating: 4.8,
      reviews: 14200,
      description: 'Sun-kissed golden beaches, Portuguese heritage churches, vibrant nightlife, and mouth-watering seafood.',
      startingPrice: 4299,
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
      tag: 'Most Popular',
      state: 'Goa, India',
      bestTime: 'Nov - Feb',
      highlights: ['Baga Beach', 'Fort Aguada', 'Old Goa Churches', 'Dudhsagar Falls']
    },
    {
      id: 'dest-manali',
      name: 'Manali',
      category: 'Mountains',
      rating: 4.9,
      reviews: 9840,
      description: 'Snow-capped Himalayan peaks, roaring river valleys, paragliding adventures, and serene pine forests.',
      startingPrice: 5999,
      image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80',
      tag: 'Adventure Hub',
      state: 'Himachal Pradesh, India',
      bestTime: 'Oct - Jun',
      highlights: ['Solang Valley', 'Rohtang Pass', 'Hadimba Temple', 'Old Manali Cafes']
    },
    {
      id: 'dest-kerala',
      name: 'Kerala Backwaters',
      category: 'Family',
      rating: 4.8,
      reviews: 11500,
      description: 'Tranquil emerald backwaters, luxurious houseboats, spice plantations, and Ayurvedic wellness retreats.',
      startingPrice: 6499,
      image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80',
      tag: "God's Own Country",
      state: 'Kerala, India',
      bestTime: 'Sep - Mar',
      highlights: ['Alleppey Houseboats', 'Munnar Tea Gardens', 'Kovalam Beach', 'Periyar Wildlife']
    },
    {
      id: 'dest-jaipur',
      name: 'Jaipur Pink City',
      category: 'Historical',
      rating: 4.7,
      reviews: 12800,
      description: 'Magnificent royal palaces, towering historic forts, bustling bazaars, and rich Rajputana grandeur.',
      startingPrice: 3499,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: 'Heritage Marvel',
      state: 'Rajasthan, India',
      bestTime: 'Oct - Mar',
      highlights: ['Hawa Mahal', 'Amber Fort', 'City Palace', 'Nahargarh Fort']
    },
    {
      id: 'dest-mysore',
      name: 'Mysore',
      category: 'Heritage',
      rating: 4.8,
      reviews: 10800,
      description: 'Royal palaces, sandalwood markets, heritage walks, and the glowing lights of Mysore Palace.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1600112356915-089abb8fc3a3?w=800&auto=format&fit=crop&q=80',
      tag: 'Royal Karnataka',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'Devaraja Market']
    },
    {
      id: 'dest-mumbai',
      name: 'Mumbai',
      category: 'City Life',
      rating: 4.7,
      reviews: 16400,
      description: 'Sea-facing promenades, iconic architecture, street food, arts, and the energy of India’s city of dreams.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
      tag: 'City Explorer',
      state: 'Maharashtra, India',
      bestTime: 'Oct - Feb',
      highlights: ['Gateway of India', 'Marine Drive', 'Elephanta Caves', 'Colaba Causeway']
    },
    {
      id: 'dest-hyderabad',
      name: 'Hyderabad',
      category: 'Food & Culture',
      rating: 4.7,
      reviews: 9300,
      description: 'Historic forts, Charminar lanes, biryani trails, pearls, and a lively modern tech culture.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1572445271230-a78b5944a659?w=800&auto=format&fit=crop&q=80',
      tag: 'Food Capital',
      state: 'Telangana, India',
      bestTime: 'Oct - Feb',
      highlights: ['Charminar', 'Golconda Fort', 'Hussain Sagar', 'Biryani Trail']
    },
    {
      id: 'dest-kashmir',
      name: 'Kashmir Valley',
      category: 'Romantic',
      rating: 4.9,
      reviews: 8600,
      description: 'Paradise on earth with mirror-like Dal Lake, traditional Shikaras, Mughal gardens, and snow slopes in Gulmarg.',
      startingPrice: 8999,
      image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&auto=format&fit=crop&q=80',
      tag: 'Paradise on Earth',
      state: 'Jammu & Kashmir, India',
      bestTime: 'Year Round',
      highlights: ['Dal Lake Shikara', 'Gulmarg Gondola', 'Pahalgam Valley', 'Sonamarg']
    },
    {
      id: 'dest-andaman',
      name: 'Andaman Islands',
      category: 'Adventure',
      rating: 4.9,
      reviews: 6700,
      description: 'Crystal turquoise waters, coral reefs, scuba diving, and white sandy beaches secluded in the Indian Ocean.',
      startingPrice: 12999,
      image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&auto=format&fit=crop&q=80',
      tag: 'Tropical Escape',
      state: 'Andaman & Nicobar Islands',
      bestTime: 'Oct - May',
      highlights: ['Radhanagar Beach', 'Scuba Diving Havelock', 'Cellular Jail', 'Elephant Beach']
    },
    {
      id: 'dest-varanasi',
      name: 'Varanasi',
      category: 'Historical',
      rating: 4.8,
      reviews: 15400,
      description: 'The spiritual capital of India on the sacred banks of Ganga, illuminated by mesmerizing evening Maha Aarti.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
      tag: 'Spiritual Capital',
      state: 'Uttar Pradesh, India',
      bestTime: 'Oct - Mar',
      highlights: ['Dashashwamedh Ghat Aarti', 'Kashi Vishwanath', 'Sunrise Boat Ride', 'Sarnath']
    },
    {
      id: 'dest-ladakh',
      name: 'Leh Ladakh',
      category: 'Adventure',
      rating: 4.9,
      reviews: 7900,
      description: 'High-altitude mountain passes, azure Pangong Lake, ancient Buddhist monasteries, and thrilling road trips.',
      startingPrice: 14500,
      image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80',
      tag: 'Land of High Passes',
      state: 'Ladakh, India',
      bestTime: 'May - Sep',
      highlights: ['Pangong Lake', 'Nubra Valley', 'Khardung La Pass', 'Thiksey Monastery']
    },

    // ============================================================
    // HIDDEN GEMS & OFFBEAT DESTINATIONS
    // Deep-tier Karnataka + India's hidden/offbeat treasures
    // ============================================================
    {
      id: 'dest-coorg',
      name: 'Coorg (Kodagu)',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 5600,
      description: 'The Scotland of India — misty coffee estates, Abbey Falls, Raja\'s Seat sunsets and the Mandalpatti peak trek in the Western Ghats.',
      startingPrice: 4499,
      image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Abbey Falls', 'Raja\'s Seat', 'Mandalpatti Peak Trek', 'Dubare Elephant Camp', 'Coffee Estate Stay']
    },
    {
      id: 'dest-chikmagalur',
      name: 'Chikmagalur',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 6100,
      description: 'Cradle of Indian coffee — climb Mullayanagiri, trek Baba Budangiri, and chase the Hebbe Falls in the Malnad hills.',
      startingPrice: 3999,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Karnataka, India',
      bestTime: 'Sep - Feb',
      highlights: ['Mullayanagiri Peak', 'Baba Budangiri', 'Kudremukh Trek', 'Hebbe Falls']
    },
    {
      id: 'dest-sakleshpur',
      name: 'Sakleshpur',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 3100,
      description: 'Star-fort ramparts at Manjarabad, the dizzying Bisle Ghat viewpoint, and the scenic Green Route railway trek through the Ghats.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Manjarabad Star Fort', 'Bisle Ghat Viewpoint', 'Green Route Railway Trek']
    },
    {
      id: 'dest-gokarna',
      name: 'Gokarna',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 9200,
      description: 'Goa\'s laid-back cousin — the Om, Kudle and Half Moon beach trek, framed by the ancient Mahabaleshwar Temple.',
      startingPrice: 3499,
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Nov - Feb',
      highlights: ['Om Beach', 'Kudle Beach', 'Half Moon Beach Trek', 'Mahabaleshwar Temple']
    },
    {
      id: 'dest-murudeshwar',
      name: 'Murudeshwar & Netrani',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 4700,
      description: 'A colossal Shiva statue on the Arabian Sea, with world-class scuba diving and coral reefs around Netrani Island.',
      startingPrice: 4299,
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - May',
      highlights: ['Giant Shiva Statue', 'Netrani Scuba Diving', 'Coral Reef Snorkeling', 'Murudeshwar Beach']
    },
    {
      id: 'dest-udupi-malpe',
      name: 'Udupi & Malpe',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 3800,
      description: 'Saintly Udupi cuisine, the surreal basaltic St. Mary\'s Islands, and the Kapu lighthouse over a shimmering coastline.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ["St. Mary's Basaltic Islands", 'Kapu Lighthouse', 'Authentic Udupi Cuisine', 'Malpe Beach']
    },
    {
      id: 'dest-karwar',
      name: 'Karwar & Devbagh',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 2600,
      description: 'Silent Kali River backwaters, mangrove kayaking, and hidden crescent beaches on the Karwar coast near Goa.',
      startingPrice: 3599,
      image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Kali River Backwaters', 'Mangrove Kayaking', 'Devbagh Beach', 'Karwar Seafood']
    },
    {
      id: 'dest-hampi',
      name: 'Hampi',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 12800,
      description: 'A surreal UNESCO landscape of boulders and royal ruins — the stone chariot, Virupaksha Temple and coracle rides on the Tungabhadra.',
      startingPrice: 3799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Virupaksha Temple', 'Stone Chariot', 'Matanga Hill Sunrise', 'Coracle Boat Ride']
    },
    {
      id: 'dest-badami',
      name: 'Badami, Aihole & Pattadakal',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 3400,
      description: 'The cradle of Chalukya architecture — rock-cut cave temples, sandstone cliffs and UNESCO temples along the Malaprabha.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Badami Cave Temples', 'Aihole Temples', 'Pattadakal Complex', 'Agastya Lake']
    },
    {
      id: 'dest-belur-halebidu',
      name: 'Belur & Halebidu',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 4100,
      description: 'Masterpieces of Hoysala stonework — the intricately carved Chennakeshava and Hoysaleswara temples.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Chennakeshava Temple', 'Hoysaleswara Temple', 'Hoysala Craftsmanship', 'Basket Weaving Village']
    },
    {
      id: 'dest-agumbe',
      name: 'Agumbe',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 2900,
      description: "The 'Cherrapunji of the South' — a rainforest kingdom of the King Cobra, Barkana Falls and unforgettable sunsets.",
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Jun - Feb',
      highlights: ['King Cobra Sanctuary', 'Barkana Falls', 'Onake Abbi Falls', 'Agumbe Sunset Point']
    },
    {
      id: 'dest-dandeli',
      name: 'Dandeli',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 5300,
      description: 'White-water rafting on the Kali, hornbill-watching in dense jungle, and the vast Supa Dam backwaters.',
      startingPrice: 3899,
      image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Karnataka, India',
      bestTime: 'Oct - May',
      highlights: ['Kali River Rafting', 'Hornbill Watching', 'Jungle Safari', 'Supa Dam']
    },
    {
      id: 'dest-kabini',
      name: 'Kabini',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 6100,
      description: 'An offbeat wildlife haven where the Black Panther prowls — river-lodge safaris in Bandipur and Nagarhole.',
      startingPrice: 6999,
      image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 Wildlife',
      state: 'Karnataka, India',
      bestTime: 'Oct - May',
      highlights: ['Black Panther Safari', 'Bandipur National Park', 'Nagarhole Reserve', 'Kabini River Lodge']
    },
    {
      id: 'dest-yana',
      name: 'Yana Caves & Vibhooti Falls',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 2200,
      description: 'Towering black crystalline karst monoliths rising from rainforest, beside the roaring Vibhooti waterfall.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Yana Rock Monoliths', 'Vibhooti Falls', 'Rainforest Trek', 'Bekal Fort']
    },
    {
      id: 'dest-honnemaradu',
      name: 'Honnemaradu',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 1800,
      description: 'Island camping and kayaking on the glassy Sharavathi backwaters — a hidden adventure escape near Shimoga.',
      startingPrice: 3199,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Sharavathi Backwaters', 'Island Camping', 'Kayaking', 'Kunchikal Falls']
    },
    {
      id: 'dest-tirthan',
      name: 'Tirthan Valley',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 3400,
      description: 'A pristine Himalayan valley of trout rivers and pine, gateway to the Great Himalayan National Park near Jibhi.',
      startingPrice: 5999,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Himachal Pradesh, India',
      bestTime: 'Mar - Jun',
      highlights: ['Great Himalayan NP', 'Tirthan River Trout', 'Jibhi Waterfall', 'Serolsar Lake']
    },
    {
      id: 'dest-chopta',
      name: 'Chopta & Tungnath',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 3900,
      description: "Mini-Switzerland meadows and the world's highest Shiva temple, with a sunrise trek to Chandrashila.",
      startingPrice: 4999,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Uttarakhand, India',
      bestTime: 'Apr - Nov',
      highlights: ['Tungnath Temple', 'Chandrashila Summit', 'Deoria Tal Lake', 'Dense Deodar Forest']
    },
    {
      id: 'dest-spiti',
      name: 'Spiti Valley',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 4500,
      description: 'A cold desert of ancient monasteries and turquoise lakes — Key Monastery, Chandratal and the Pin Valley.',
      startingPrice: 7999,
      image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Himachal Pradesh, India',
      bestTime: 'May - Oct',
      highlights: ['Key Monastery', 'Chandratal Lake', 'Pin Valley NP', 'Kaza Old Town']
    },
    {
      id: 'dest-zanskar',
      name: 'Zanskar',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 2100,
      description: 'The legendary chadar trek across a frozen river, plus cliff-hung Phugtal monastery in the remote Zanskar ranges.',
      startingPrice: 8999,
      image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Ladakh, India',
      bestTime: 'Jan - Feb, Jun - Sep',
      highlights: ['Chadar Trek', 'Phugtal Monastery', 'Zangla Valley', 'Panikhar Meadows']
    },
    {
      id: 'dest-gurez',
      name: 'Gurez Valley',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 1500,
      description: 'A high-altitude valley of wild meadows and the Habba Khatoon peak, along the Kishanganga river in Kashmir.',
      startingPrice: 6999,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Jammu & Kashmir, India',
      bestTime: 'May - Sep',
      highlights: ['Habba Khatoon Peak', 'Kishanganga River', 'Dawar Village', 'Sheikh Baba Sahib Shrine']
    },
    {
      id: 'dest-ziro',
      name: 'Ziro Valley',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 1600,
      description: 'Home of the Apatani tribe — terraced paddy fields, bamboo villages and the famous Ziro Music Festival.',
      startingPrice: 5999,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Arunachal Pradesh, India',
      bestTime: 'Sep - Nov',
      highlights: ['Apatani Villages', 'Paddy Terraces', 'Ziro Music Festival', 'Talent Hapoli']
    },
    {
      id: 'dest-mawlynnong',
      name: 'Mawlynnong & Root Bridges',
      category: 'Hidden Gems',
      rating: 4.9,
      reviews: 3800,
      description: 'Asia\'s cleanest village, famous for living root bridges, the Nohkalikai waterfall and Khasi hospitality.',
      startingPrice: 4999,
      image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Meghalaya, India',
      bestTime: 'Oct - May',
      highlights: ['Living Root Bridges', 'Nohkalikai Falls', 'Double Decker Bridge', 'Sky Walk']
    },
    {
      id: 'dest-majuli',
      name: 'Majuli Island',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 1700,
      description: 'The world\'s largest river island on the Brahmaputra — Vaishnavite Satras, mask-making and magical sunsets.',
      startingPrice: 4499,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Assam, India',
      bestTime: 'Sep - Mar',
      highlights: ['Satras & Monasteries', 'Mask Making', 'Mising Culture', 'Brahmaputra Sunset']
    },
    {
      id: 'dest-daringbadi',
      name: 'Daringbadi',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 1900,
      description: 'The "Kashmir of Odisha" — pine forests, coffee gardens, waterfalls and chill winter mists in the Eastern Ghats.',
      startingPrice: 3999,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Odisha, India',
      bestTime: 'Oct - Feb',
      highlights: ['Daringbadi Pine Forest', 'Coffee Gardens', 'Bhimkund Waterfall', 'Hill View Point']
    },
    {
      id: 'dest-dzukou',
      name: "Dzükou Valley",
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 1400,
      description: 'The Valley of Flowers of the North-East, blooming in lilies and rhododendrons on the Nagaland–Manipur border.',
      startingPrice: 5499,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Nagaland, India',
      bestTime: 'Jun - Sep',
      highlights: ['Seasonal Blooms', 'Japfu Peak Trek', 'Dzükou Camp', 'Shilloi Lake']
    },
    {
      id: 'dest-lonar',
      name: 'Lonar Crater Lake',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 2400,
      description: 'A rare meteorite-created saline lake ringed by ancient Hindu temples in Maharashtra\'s Buldhana district.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Maharashtra, India',
      bestTime: 'Oct - Mar',
      highlights: ['Meteor Crater Lake', 'Daityasudan Temple', 'Gomukh Temple', 'Bird Watching']
    },
    {
      id: 'dest-gandikota',
      name: 'Gandikota',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 2800,
      description: 'India\'s Grand Canyon — a dramatic gorge over the Penna river, near the vast Belum Caves in Andhra Pradesh.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Andhra Pradesh, India',
      bestTime: 'Oct - Mar',
      highlights: ['Gorge Viewpoint', 'Belum Caves', 'Gandikota Fort', 'Penna River']
    },
    {
      id: 'dest-vattakanal',
      name: 'Vattakanal',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 2100,
      description: '"Little Kashmir" — foggy pine forests, cliff viewpoints and artsy cafés above Kodaikanal in the Palani Hills.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Tamil Nadu, India',
      bestTime: 'Oct - Mar',
      highlights: ['Pine Forest', 'Dolphin\'s Nose View', 'Kodaikanal Lake', 'Coffee Estates']
    },
    {
      id: 'dest-chembra',
      name: 'Chembra & Gavi',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 2700,
      description: 'The heart-shaped Chembra lake above Wayanad, and the eco-tourism paradise of Gavi deep in the Periyar forests.',
      startingPrice: 4999,
      image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Kerala, India',
      bestTime: 'Sep - Mar',
      highlights: ['Heart-Shaped Lake', 'Chembra Peak Trek', 'Gavi Eco-Tourism', 'Periyar Wildlife']
    },
    {
      id: 'dest-kolukkumalai',
      name: 'Kolukkumalai',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 1800,
      description: 'The world\'s highest organic tea estate, with a dramatic sunrise over Tamil Nadu and Kerala\'s cloud forests.',
      startingPrice: 4599,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
      tag: '✨ Hidden Gem',
      state: 'Tamil Nadu, India',
      bestTime: 'Sep - Feb',
      highlights: ['Highest Tea Estate', 'Sunrise Viewpoint', 'Tea Factory Tour', 'Munnar Roads']
    },
    {
      id: 'dest-velas',
      name: 'Velas Turtle Beach',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 1200,
      description: 'A protected Olive Ridley turtle nesting beach on the Konkan coast — a rare, family-friendly nature escape.',
      startingPrice: 3199,
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Maharashtra, India',
      bestTime: 'Feb - Apr',
      highlights: ['Olive Ridley Nesting', 'Velas Turtle Festival', 'Bankot Fort', 'Konkan Coast']
    },
    {
      id: 'dest-jawai',
      name: 'Jawai Leopard Hills',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 2000,
      description: 'Leopard country — wild leopards basking on granite rocks, with rustic village stays in southern Rajasthan.',
      startingPrice: 6999,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 Wildlife',
      state: 'Rajasthan, India',
      bestTime: 'Oct - Mar',
      highlights: ['Leopard Safari', 'Granite Hills', 'Village Homestay', 'Jawai Dam']
    },
    {
      id: 'dest-belum',
      name: 'Belum Caves',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 2300,
      description: 'Longest cave system in the Indian plains — vast underground chambers and stalactite formations in Andhra Pradesh.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Andhra Pradesh, India',
      bestTime: 'Year Round',
      highlights: ['Underground Chambers', 'Stalactite Formations', 'Patalganaga Tunnel', 'Belum Museum']
    },

    // ============================================================
    // MORE PLACES OF INDIA — ESPECIALLY DEEP-TIER KARNATAKA
    // Cities, districts, temples, forests, waterfalls & heritage
    // ============================================================

    // ---------------- KARNATAKA ----------------
    {
      id: 'dest-bengaluru',
      name: 'Bangalore (Bengaluru)',
      category: 'Family',
      rating: 4.7,
      reviews: 15400,
      description: 'The Garden City — Lalbagh Botanical Garden, Cubbon Park, royal palaces, tech parks and a great food scene.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
      tag: '😍 Family',
      state: 'Karnataka, India',
      bestTime: 'Year Round',
      highlights: ['Lalbagh Botanical Garden', 'Cubbon Park', 'Tipu Sultan\'s Summer Palace', 'ISRO Headquarters', 'Brigade Road']
    },
    {
      id: 'dest-nandihills',
      name: 'Nandi Hills',
      category: 'Mountains',
      rating: 4.6,
      reviews: 8300,
      description: 'A misty hilltop near Bengaluru with breathtaking sunrise, Tipu\'s summer fort and the ancient Bhoga Nandeeshwara temple.',
      startingPrice: 3499,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
      tag: '🏔️ Hills',
      state: 'Karnataka, India',
      bestTime: 'Jun - Feb',
      highlights: ['Sunrise Point', 'Tipu\'s Drop Viewpoint', 'Bhoga Nandeeshwara Temple', 'Amrita Sarovar Lake']
    },
    {
      id: 'dest-srirangapatna',
      name: 'Srirangapatna',
      category: 'Historical',
      rating: 4.7,
      reviews: 4700,
      description: 'An island fortress on the Cauvery — Tipu Sultan\'s summer palace, the Ranganathaswamy temple and the Battle of Seringapatam sites.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🏰 Heritage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Daria Daulat Bagh', 'Ranganathaswamy Temple', 'Tipu\'s Death Spot', 'Water Gate & Dungeon']
    },
    {
      id: 'dest-ranganathittu',
      name: 'Ranganathittu Bird Sanctuary',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 2900,
      description: 'A serene Cauvery riverine haven with boat safaris through islands teeming with herons, ibis, cormorants and crocodiles.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Nov - Jun',
      highlights: ['Boat Safari', 'Migratory Birds', 'Mugger Crocodiles', 'Islands of the Cauvery']
    },
    {
      id: 'dest-shivanasamudra',
      name: 'Shivanasamudra Falls',
      category: 'Adventure',
      rating: 4.6,
      reviews: 5100,
      description: 'The twin horseshoe waterfalls of Gaganachukki & Barachukki, beside one of Asia\'s oldest hydroelectric plants.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80',
      tag: '💧 Falls',
      state: 'Karnataka, India',
      bestTime: 'Oct - Dec',
      highlights: ['Gaganachukki Falls', 'Barachukki Falls', 'Old KRS Hydro Plant', 'Ranganathittu Bird Park']
    },
    {
      id: 'dest-bandipur',
      name: 'Bandipur National Park',
      category: 'Adventure',
      rating: 4.8,
      reviews: 6400,
      description: 'A prime tiger reserve on the Mysore–Ooty route, with jungle safaris, elephants, leopards and the Nilgiri Biosphere.',
      startingPrice: 4999,
      image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 Wildlife',
      state: 'Karnataka, India',
      bestTime: 'Oct - May',
      highlights: ['Tiger Safari', 'Elephant Herds', 'Sambar & Gaurs', 'Bamboo Forests']
    },
    {
      id: 'dest-kudremukh',
      name: 'Kudremukh National Park',
      category: 'Mountains',
      rating: 4.7,
      reviews: 2600,
      description: 'A trekker\'s paradise of rolling grassland sholas and the mighty Kudremukh peak shaped like a horse\'s face.',
      startingPrice: 3499,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🏔️ Trek',
      state: 'Karnataka, India',
      bestTime: 'Sep - Feb',
      highlights: ['Kudremukh Peak Trek', 'Rolling Shola Grasslands', 'Gangamoola Spring', 'Lion-tailed Macaques']
    },
    {
      id: 'dest-kodachadri',
      name: 'Kodachadri',
      category: 'Mountains',
      rating: 4.6,
      reviews: 1900,
      description: 'A sacred forested peak above the Mookambika temple, with the hidden Hidlumane waterfall and a dramatic stone trek.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Sep - Feb',
      highlights: ['Hidlumane Falls', 'Kodachadri Peak', 'Mookambika Wildlife', 'Mistry Caves']
    },
    {
      id: 'dest-kollur-mookambika',
      name: 'Kollur Mookambika Temple',
      category: 'Historical',
      rating: 4.8,
      reviews: 3900,
      description: 'One of the 18 Shakti Peethas, wedged between the Kodachadri hills and the Arabian Sea, at the mouth of the Souparnika.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Mookambika Devi Temple', 'Kumaraparvatha Trek', 'Souparnika River', 'Shakti Peetha']
    },
    {
      id: 'dest-jog-falls',
      name: 'Jog Falls (Sharavathi)',
      category: 'Adventure',
      rating: 4.8,
      reviews: 7600,
      description: 'One of India\'s highest waterfalls — four cascades plunging 253 m off the Sharavathi river in the Western Ghats.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80',
      tag: '💧 Falls',
      state: 'Karnataka, India',
      bestTime: 'Aug - Dec',
      highlights: ['Raja, Rocket & Rani Falls', 'Sharavathi Valley View', 'Linganamakki Dam', 'Viewpoint & Steps']
    },
    {
      id: 'dest-unchalli',
      name: 'Sirsi & Unchalli Falls',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 1400,
      description: 'A hidden forested canyon where the Aghanashini river leaps into the Unchalli (Keeni) falls, deep in the Uttara Kannada jungle.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Sep - Jan',
      highlights: ['Unchalli Falls', 'Marikamba Temple', 'Aghanashini River', 'Banks of the Forest']
    },
    {
      id: 'dest-banavasi',
      name: 'Banavasi',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 1100,
      description: 'One of Karnataka\'s oldest towns — the ancient Kadamba capital with the intricately carved Madhukeshwara temple.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Madhukeshwara Temple', 'Kadamba Heritage', 'Varada River', 'Oldest Town of Karnataka']
    },
    {
      id: 'dest-sringeri',
      name: 'Sringeri',
      category: 'Hidden Gems',
      rating: 4.8,
      reviews: 3300,
      description: 'The erstwhile seat of the Adi Shankaracharya matha, set in a gorge of the Tunga river amid lush Western Ghats.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Sringeri Sharada Peetham', 'Vidyashankara Temple', 'Tunga River', 'Malathi & Dattatreya Peetha']
    },
    {
      id: 'dest-horanadu',
      name: 'Horanadu',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 3600,
      description: 'A serene forest temple of Annapurneshwari in the Chikkamagaluru hills, known for its free prasadam meals.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Annapurneshwari Temple', 'Lush Western Ghats', 'Bhadra River', 'Kalasa Nearby']
    },
    {
      id: 'dest-dharmasthala',
      name: 'Dharmasthala',
      category: 'Historical',
      rating: 4.7,
      reviews: 4200,
      description: 'A grand pilgrim town on the Netravati with the Manjunatha temple, a giant gopuram and a famous car festival.',
      startingPrice: 2499,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Manjunatha Temple', 'Shri Kshetra Dharmasthala', 'Netravati River', 'Bahubali Statue']
    },
    {
      id: 'dest-kukke-subrahmanya',
      name: 'Kukke Subrahmanya',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 4000,
      description: 'A sacred temple to Kartikeya beside the Kumaradhara river, nestled at the foot of the Western Ghats.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Subrahmanya Temple', 'Kumaradhara River', 'Kumara Parvatha', 'Madhur Temple Nearby']
    },
    {
      id: 'dest-shravanabelagola',
      name: 'Shravanabelagola',
      category: 'Historical',
      rating: 4.7,
      reviews: 3800,
      description: 'Home to the colossal 57-ft Gommateshwara (Bahubali) monolith, the world\'s tallest free-standing statue, carved atop a granite hill.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🏛️ Heritage',
      state: 'Karnataka, India',
      bestTime: 'Sep - Feb',
      highlights: ['Gommateshwara Statue', 'Indragiri Hill', 'Chandragiri Hill', 'Ancient Jain Basadis']
    },
    {
      id: 'dest-melukote',
      name: 'Melukote',
      category: 'Hidden Gems',
      rating: 4.6,
      reviews: 1800,
      description: 'A sacred hill town with the Cheluvanarayana Swamy temple, famed for the Vairamudi festival and rock boundaries.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Cheluvanarayana Swamy Temple', 'Vairamudi Festival', 'Tirumala Hill', 'Walnut Grove']
    },
    {
      id: 'dest-somanathapura',
      name: 'Somanathapura',
      category: 'Historical',
      rating: 4.7,
      reviews: 2300,
      description: 'The exquisite Chennakeshava temple, a star-shaped Hoysala masterpiece on the banks of the Cauvery near Mysore.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🏛️ Heritage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Chennakeshava Temple', 'Hoysala Carvings', 'Star-shaped Platform', 'Banks of the Cauvery']
    },
    {
      id: 'dest-talakadu',
      name: 'Talakadu',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 1600,
      description: 'Mysterious white-sand dunes and buried Panchalinga temples on a curve of the Cauvery, with an eerie backstory.',
      startingPrice: 2599,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Sand Dunes', 'Panchalinga Temples', 'Cauvery River', 'Talakadu Festival']
    },
    {
      id: 'dest-bylakuppe',
      name: 'Bylakuppe (Golden Temple)',
      category: 'Hidden Gems',
      rating: 4.7,
      reviews: 3100,
      description: 'A vast Tibetan Buddhist settlement with the glittering Namdroling monastery and its towering golden statues.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Year Round',
      highlights: ['Namdroling Monastery', 'Golden Buddha Statues', 'Tibetan Cuisine', 'Kushalnagar Nearby']
    },
    {
      id: 'dest-mangalore',
      name: 'Mangalore (Mangaluru)',
      category: 'Beaches',
      rating: 4.6,
      reviews: 8900,
      description: 'A breezy coastal city with golden beaches, the Kadri Manjunatha temple, and a vibrant blend of Konkani & Tulu food.',
      startingPrice: 3499,
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop&q=80',
      tag: '🌊 Coastal',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Panambur Beach', 'Kadri Manjunatha Temple', 'Tannirbavi Beach', 'Sultan Battery']
    },
    {
      id: 'dest-maravanthe',
      name: 'Maravanthe Beach',
      category: 'Hidden Gems',
      rating: 4.5,
      reviews: 1300,
      description: 'A rare stretch where the NH highway runs between the Arabian Sea and the Souparnika river — a gorgeous coastal ribbon.',
      startingPrice: 3199,
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop&q=80',
      tag: '🖤 Offbeat',
      state: 'Karnataka, India',
      bestTime: 'Oct - Feb',
      highlights: ['Sea-River Corridor', 'Sunset Point', 'Maravanthe Islands', 'Nearby Kundapura']
    },
    {
      id: 'dest-bidar',
      name: 'Bidar',
      category: 'Historical',
      rating: 4.6,
      reviews: 2100,
      description: 'The Bahmani capital with a mighty fort, the grand Rangeen Mahal frescoes, and the impressive Bidar madrasa.',
      startingPrice: 2499,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🏰 Heritage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Bidar Fort', 'Rangeen Mahal', 'Bidar Madrasa', 'Bahmani Tombs']
    },
    {
      id: 'dest-bijapur',
      name: 'Bijapur & Gol Gumbaz',
      category: 'Historical',
      rating: 4.7,
      reviews: 4100,
      description: 'Home to the colossal Gol Gumbaz — the world\'s second-largest dome — plus the elegant Ibrahim Rauza and old fort.',
      startingPrice: 2799,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🏛️ Heritage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Gol Gumbaz', 'Ibrahim Rauza', 'Bijapur Fort', 'Jama Masjid']
    },
    {
      id: 'dest-calaburagi',
      name: 'Kalaburagi (Gulbarga)',
      category: 'Historical',
      rating: 4.5,
      reviews: 1600,
      description: 'The ancient Bahmani citadel with a stunning fort, a unique Jama Masjid and the Sharanabasaveshwara temple.',
      startingPrice: 2499,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🏰 Heritage',
      state: 'Karnataka, India',
      bestTime: 'Oct - Mar',
      highlights: ['Gulbarga Fort', 'Jama Masjid', 'Sharanabasaveshwara Temple', 'Bahmani Heritage']
    },

    // ---------------- REST OF INDIA ----------------
    {
      id: 'dest-rishikesh',
      name: 'Rishikesh',
      category: 'Adventure',
      rating: 4.8,
      reviews: 12900,
      description: 'The yoga capital of the world — white-water rafting on the Ganges, the iconic Laxman Jhula and ashram-lined ghats.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80',
      tag: '🧗 Adventure',
      state: 'Uttarakhand, India',
      bestTime: 'Sep - Nov & Feb - May',
      highlights: ['Ganga River Rafting', 'Laxman Jhula', 'Triveni Ghat Aarti', 'Beatles Ashram']
    },
    {
      id: 'dest-amritsar',
      name: 'Amritsar & Golden Temple',
      category: 'Historical',
      rating: 4.9,
      reviews: 18200,
      description: 'The shimmering Golden Temple (Harmandir Sahib), the emotional Wagah Border ceremony and sumptuous Amritsari food.',
      startingPrice: 3499,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Punjab, India',
      bestTime: 'Oct - Mar',
      highlights: ['Golden Temple', 'Wagah Border Ceremony', 'Jallianwala Bagh', 'Amritsari Kulcha']
    },
    {
      id: 'dest-tirupati',
      name: 'Tirupati Balaji',
      category: 'Historical',
      rating: 4.8,
      reviews: 22600,
      description: 'The world-famous Tirumala Venkateswara temple, one of the richest and most-visited pilgrimages in the world.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Andhra Pradesh, India',
      bestTime: 'Year Round',
      highlights: ['Tirumala Temple', 'Seven Hills', 'Sri Vari Laddu', 'Tirupati Botanical Garden']
    },
    {
      id: 'dest-madurai',
      name: 'Madurai',
      category: 'Historical',
      rating: 4.7,
      reviews: 10600,
      description: 'The temple city crowned by the towering Meenakshi Amman temple with its colourful gopurams and daily ceremonies.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🏛️ Heritage',
      state: 'Tamil Nadu, India',
      bestTime: 'Oct - Mar',
      highlights: ['Meenakshi Amman Temple', 'Thirumalai Nayak Palace', 'Madurai Jigarthanda', 'Pudhu Mandapam']
    },
    {
      id: 'dest-thanjavur',
      name: 'Thanjavur (Big Temple)',
      category: 'Historical',
      rating: 4.8,
      reviews: 7000,
      description: 'The UNESCO-listed Brihadeeswarar temple — a Chola giant with a 66-m shikhara that has stood for a thousand years.',
      startingPrice: 2999,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Tamil Nadu, India',
      bestTime: 'Oct - Mar',
      highlights: ['Brihadeeswarar Temple', 'Thanjavur Palace', 'Saraswati Mahal Library', 'Thanjavur Perungudi']
    },
    {
      id: 'dest-mahabalipuram',
      name: 'Mahabalipuram',
      category: 'Historical',
      rating: 4.7,
      reviews: 6800,
      description: 'A UNESCO beachside treasure — the Shore Temple, monolithic Pancha Rathas and Arjuna\'s Penance bas-relief.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Tamil Nadu, India',
      bestTime: 'Nov - Feb',
      highlights: ['Shore Temple', 'Pancha Rathas', 'Arjuna\'s Penance', 'Krishna\'s Butterball']
    },
    {
      id: 'dest-pondicherry',
      name: 'Pondicherry (Puducherry)',
      category: 'Romantic',
      rating: 4.6,
      reviews: 9700,
      description: 'A French-colonial seaside town of pastel streets, the Sri Aurobindo Ashram, Auroville and serene beaches.',
      startingPrice: 3999,
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&auto=format&fit=crop&q=80',
      tag: '💑 Romantic',
      state: 'Puducherry, India',
      bestTime: 'Oct - Mar',
      highlights: ['French Quarter', 'Auroville', 'Paradise Beach', 'Promenade & Rock Beach']
    },
    {
      id: 'dest-udaipur',
      name: 'Udaipur',
      category: 'Romantic',
      rating: 4.8,
      reviews: 13900,
      description: 'The City of Lakes — Lake Pichola, the floating Lake Palace, City Palace and the Aravalli at sunset.',
      startingPrice: 5499,
      image: 'https://images.unsplash.com/photo-1600112356915-089abb8fc3a3?w=800&auto=format&fit=crop&q=80',
      tag: '💑 Romantic',
      state: 'Rajasthan, India',
      bestTime: 'Sep - Mar',
      highlights: ['Lake Pichola', 'City Palace', 'Jag Mandir', 'Kumbhalgarh Fort Day Trip']
    },
    {
      id: 'dest-jaisalmer',
      name: 'Jaisalmer',
      category: 'Adventure',
      rating: 4.8,
      reviews: 9200,
      description: 'The Golden City — a living fort of golden sandstone, the Thar desert, and camel safaris to Sam sand dunes.',
      startingPrice: 5999,
      image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&auto=format&fit=crop&q=80',
      tag: '🏜️ Desert',
      state: 'Rajasthan, India',
      bestTime: 'Oct - Mar',
      highlights: ['Jaisalmer Fort', 'Sam Sand Dunes', 'Camel Safari', 'Patwon Ki Haveli']
    },
    {
      id: 'dest-jodhpur',
      name: 'Jodhpur',
      category: 'Historical',
      rating: 4.7,
      reviews: 9800,
      description: 'The Blue City beneath the mighty Mehrangarh Fort — a kaleidoscope of indigo houses and royal havelis.',
      startingPrice: 4999,
      image: 'https://images.unsplash.com/photo-1600112356915-089abb8fc3a3?w=800&auto=format&fit=crop&q=80',
      tag: '🏰 Heritage',
      state: 'Rajasthan, India',
      bestTime: 'Oct - Mar',
      highlights: ['Mehrangarh Fort', 'Jaswant Thada', 'Blue City Old Town', 'Umaid Bhawan Palace']
    },
    {
      id: 'dest-darjeeling',
      name: 'Darjeeling',
      category: 'Mountains',
      rating: 4.7,
      reviews: 8400,
      description: 'The Queen of the Hills — steam toy trains, sprawling tea gardens and front-row Kanchenjunga views.',
      startingPrice: 4999,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
      tag: '🏔️ Hills',
      state: 'West Bengal, India',
      bestTime: 'Mar - May & Sep - Nov',
      highlights: ['Darjeeling Toy Train', 'Tiger Hill Sunrise', 'Happy Valley Tea Estate', 'Batasia Loop']
    },
    {
      id: 'dest-gangtok',
      name: 'Gangtok & (Sikkim)',
      category: 'Mountains',
      rating: 4.7,
      reviews: 6500,
      description: 'The Sikkimese capital of prayer flags — the Tsomgo Lake, Nathula Pass and Rumtek monastery at the Himalayan edge.',
      startingPrice: 5499,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🏔️ Hills',
      state: 'Sikkim, India',
      bestTime: 'Mar - May & Sep - Nov',
      highlights: ['Tsomgo Lake', 'Nathula Pass', 'Rumtek Monastery', 'MG Marg']
    },
    {
      id: 'dest-ajanta-ellora',
      name: 'Ajanta & Ellora Caves',
      category: 'Historical',
      rating: 4.9,
      reviews: 5600,
      description: 'Magnificent rock-cut cave temples of Buddhist, Hindu and Jain art — including the monumental Kailasa at Ellora.',
      startingPrice: 3999,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Maharashtra, India',
      bestTime: 'Oct - Mar',
      highlights: ['Kailasa Temple', 'Ajanta Frescoes', 'Ellora Caves', 'Gautam Buddha Statues']
    },
    {
      id: 'dest-khajuraho',
      name: 'Khajuraho',
      category: 'Historical',
      rating: 4.6,
      reviews: 4900,
      description: 'UNESCO temples famous for their intricate, expressive stone carvings — a celebration of life in sandstone.',
      startingPrice: 3999,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Madhya Pradesh, India',
      bestTime: 'Oct - Feb',
      highlights: ['Kandariya Mahadeva Temple', 'Western Group Temples', 'Light & Sound Show', 'Sunset at Chausath Yogini']
    },
    {
      id: 'dest-konark',
      name: 'Konark Sun Temple',
      category: 'Historical',
      rating: 4.7,
      reviews: 4200,
      description: 'A UNESCO sun-chariot temple carved as a colossal stone wheel, on the Konark coastline of Puri.',
      startingPrice: 3299,
      image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Odisha, India',
      bestTime: 'Oct - Feb',
      highlights: ['Sun Temple', 'Chandrabhaga Beach', 'Konark Dance Festival', 'Nata Mandira']
    },
    {
      id: 'dest-rannofkutch',
      name: 'Rann of Kutch',
      category: 'Adventure',
      rating: 4.8,
      reviews: 6100,
      description: 'The surreal white salt desert of the Great Rann — full-moon camel rides and the colourful Rann Utsav festival.',
      startingPrice: 6499,
      image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&auto=format&fit=crop&q=80',
      tag: '🏜️ Desert',
      state: 'Gujarat, India',
      bestTime: 'Nov - Feb',
      highlights: ['White Salt Desert', 'Rann Utsav', 'Kalo Dungar', 'Kutch Handicrafts']
    },
    {
      id: 'dest-ranthambore',
      name: 'Ranthambore',
      category: 'Adventure',
      rating: 4.8,
      reviews: 7300,
      description: 'India\'s most famous tiger reserve — jungle safaris amid ancient ruins and dry deciduous forest.',
      startingPrice: 6999,
      image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 Wildlife',
      state: 'Rajasthan, India',
      bestTime: 'Oct - Jun',
      highlights: ['Bengal Tiger Safari', 'Ranthambore Fort', 'Padam Talao', 'Leopard & Sloth Bear']
    },
    {
      id: 'dest-valleyofflowers',
      name: 'Valley of Flowers',
      category: 'Mountains',
      rating: 4.8,
      reviews: 2900,
      description: 'A UNESCO Himalayan valley that bursts into a carpet of rare alpine blooms each monsoon, trekkable from Govindghat.',
      startingPrice: 5999,
      image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80',
      tag: '🌿 UNESCO',
      state: 'Uttarakhand, India',
      bestTime: 'Jul - Sep',
      highlights: ['Alpine Blooms', 'Hemkund Sahib Trek', 'Pushpawati River', 'Glacier Views']
    },
    {
      id: 'dest-ujjain',
      name: 'Ujjain',
      category: 'Historical',
      rating: 4.7,
      reviews: 5800,
      description: 'The holy city of the Mahakaleshwar Jyotirlinga and the grand Simhastha Kumbh Mela on the Shipra river.',
      startingPrice: 2499,
      image: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80',
      tag: '🕉️ Pilgrimage',
      state: 'Madhya Pradesh, India',
      bestTime: 'Oct - Mar',
      highlights: ['Mahakaleshwar Jyotirlinga', 'Bhasma Aarti', 'Kaliadeh Palace', 'Shipra Ghats']
    }
  ],

  // 2. Flights Mock Data
  flights: [
    {
      id: 'FL-601',
      airline: 'IndiGo Airlines',
      flightNumber: '6E-2044',
      logo: '✈️',
      fromCode: 'DEL',
      fromCity: 'New Delhi',
      toCode: 'GOI',
      toCity: 'Goa',
      departureTime: '06:30',
      arrivalTime: '09:05',
      duration: '2h 35m',
      stops: 'Non-stop',
      price: 4299,
      seatsLeft: 4,
      baggage: '15 kg Check-in, 7 kg Cabin'
    },
    {
      id: 'FL-602',
      airline: 'Air India',
      flightNumber: 'AI-883',
      logo: '🇮🇳',
      fromCode: 'BOM',
      fromCity: 'Mumbai',
      toCode: 'GOI',
      toCity: 'Goa',
      departureTime: '08:15',
      arrivalTime: '09:30',
      duration: '1h 15m',
      stops: 'Non-stop',
      price: 3199,
      seatsLeft: 7,
      baggage: '25 kg Check-in, 7 kg Cabin'
    },
    {
      id: 'FL-603',
      airline: 'Vistara',
      flightNumber: 'UK-921',
      logo: '✨',
      fromCode: 'BLR',
      fromCity: 'Bengaluru',
      toCode: 'COK',
      toCity: 'Kochi (Kerala)',
      departureTime: '11:00',
      arrivalTime: '12:15',
      duration: '1h 15m',
      stops: 'Non-stop',
      price: 3699,
      seatsLeft: 5,
      baggage: '15 kg Check-in, 7 kg Cabin'
    },
    {
      id: 'FL-604',
      airline: 'Akasa Air',
      flightNumber: 'QP-1352',
      logo: '⚡',
      fromCode: 'MAA',
      fromCity: 'Chennai',
      toCode: 'GOI',
      toCity: 'Goa',
      departureTime: '14:20',
      arrivalTime: '16:00',
      duration: '1h 40m',
      stops: 'Non-stop',
      price: 3899,
      seatsLeft: 9,
      baggage: '15 kg Check-in, 7 kg Cabin'
    }
  ],

  // 3. Stays / Hotels Mock Data
  stays: [
    {
      id: 'stay-1',
      name: 'Ocean Pearl Luxury Beach Resort',
      category: 'Resorts',
      location: 'Calangute Beach, Goa',
      rating: 4.8,
      reviews: 840,
      pricePerNight: 3499,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
      amenities: ['Free High-Speed Wi-Fi', 'Infinity Pool', 'Complimentary Breakfast', 'Private Beach Access', 'Spa & Wellness', 'Free Valet Parking'],
      tag: 'Best Seller'
    },
    {
      id: 'stay-2',
      name: 'Himalayan Pine Cliff Villa',
      category: 'Villas',
      location: 'Old Manali, Himachal Pradesh',
      rating: 4.9,
      reviews: 520,
      pricePerNight: 5299,
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&auto=format&fit=crop&q=80',
      amenities: ['Mountain View Balcony', 'Bonfire & BBQ', 'Kitchenette', 'Heated Rooms', 'Wi-Fi', 'Pet Friendly'],
      tag: 'Superhost'
    },
    {
      id: 'stay-3',
      name: 'Heritage Haveli & Boutique Palace',
      category: 'Hotels',
      location: 'Old City, Jaipur',
      rating: 4.7,
      reviews: 690,
      pricePerNight: 2899,
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&auto=format&fit=crop&q=80',
      amenities: ['Rooftop Restaurant', 'Heritage Courtyard', 'Cultural Folk Show', 'Wi-Fi', 'Swimming Pool'],
      tag: 'Heritage Living'
    },
    {
      id: 'stay-4',
      name: 'Emerald Palm Backwater Homestay',
      category: 'Homestays',
      location: 'Alleppey, Kerala',
      rating: 4.9,
      reviews: 410,
      pricePerNight: 2499,
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&auto=format&fit=crop&q=80',
      amenities: ['Canal View', 'Authentic Kerala Meals', 'Shikara Boat Rides', 'Village Walk Tour', 'Free Wi-Fi'],
      tag: 'Eco Friendly'
    }
  ],

  // 4. Rides Mock Data
  rides: [
    {
      type: 'bike',
      name: 'Genie Bike',
      icon: '🏍️',
      eta: '2 mins away',
      capacity: '1 person',
      fare: 89,
      distance: '4.2 km',
      description: 'Beat the traffic, super fast & economical'
    },
    {
      type: 'auto',
      name: 'Genie Auto',
      icon: '🛺',
      eta: '3 mins away',
      capacity: '3 persons',
      fare: 129,
      distance: '4.2 km',
      description: 'Pocket-friendly local auto with digital meter'
    },
    {
      type: 'mini',
      name: 'Genie Mini',
      icon: '🚕',
      eta: '4 mins away',
      capacity: '4 persons',
      fare: 179,
      distance: '4.2 km',
      description: 'Affordable compact AC hatchback rides'
    },
    {
      type: 'sedan',
      name: 'Genie Prime Sedan',
      icon: '🚘',
      eta: '5 mins away',
      capacity: '4 persons',
      fare: 249,
      distance: '4.2 km',
      description: 'Top-rated drivers with spacious legroom & Wi-Fi'
    },
    {
      type: 'suv',
      name: 'Genie Prime SUV',
      icon: '🚙',
      eta: '6 mins away',
      capacity: '6 persons',
      fare: 399,
      distance: '4.2 km',
      description: 'Extra luggage room & luxury seats for groups'
    }
  ],

  // Mock Drivers
  mockDrivers: [
    { name: 'Ramesh Sharma', rating: 4.9, trips: 3420, vehicle: 'Maruti Dzire (Silver)', plate: 'GA-03-AB-4921', phone: '+91 98765 43210' },
    { name: 'Praveen Kumar', rating: 4.8, trips: 2180, vehicle: 'Hyundai i20 (White)', plate: 'GA-07-K-8812', phone: '+91 98123 45678' },
    { name: 'Sandeep Naik', rating: 4.9, trips: 4100, vehicle: 'Toyota Innova (Black)', plate: 'GA-01-X-1940', phone: '+91 98456 78901' }
  ],

  // 5. Food Discovery Mock Data
  restaurants: [
    {
      id: 'rest-1',
      name: 'Coastal Spice Beach Shack',
      cuisine: 'Goan • Seafood • Coastal',
      rating: 4.8,
      deliveryTime: '25 min',
      priceRange: '₹₹',
      location: 'Baga Road, Goa',
      image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
      menu: [
        { id: 'f1', name: 'Goan Prawn Curry with Steamed Rice', price: 380, isVeg: false, tag: 'Bestseller' },
        { id: 'f2', name: 'Butter Garlic Crab', price: 540, isVeg: false, tag: 'Chef Special' },
        { id: 'f3', name: 'Goan Fish Thali', price: 290, isVeg: false, tag: 'Popular' },
        { id: 'f4', name: 'Bebinca Traditional Dessert', price: 160, isVeg: true, tag: 'Sweet' }
      ]
    },
    {
      id: 'rest-2',
      name: 'Royal Heritage Biryani Hub',
      cuisine: 'Hyderabadi • Mughlai • Kebabs',
      rating: 4.7,
      deliveryTime: '30 min',
      priceRange: '₹₹',
      location: 'Heritage Lane',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
      menu: [
        { id: 'f5', name: 'Hyderabadi Dum Chicken Biryani', price: 320, isVeg: false, tag: 'Must Try' },
        { id: 'f6', name: 'Mutton Galouti Kebab (4 pcs)', price: 380, isVeg: false, tag: 'Rich' },
        { id: 'f7', name: 'Paneer Tikka Biryani', price: 280, isVeg: true, tag: 'Veg Special' },
        { id: 'f8', name: 'Double Ka Meetha', price: 140, isVeg: true, tag: 'Dessert' }
      ]
    },
    {
      id: 'rest-3',
      name: 'Green Oasis Pure Veg & South Delights',
      cuisine: 'South Indian • Dosa • Thali',
      rating: 4.9,
      deliveryTime: '20 min',
      priceRange: '₹',
      location: 'Station Road',
      image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=800&auto=format&fit=crop&q=80',
      menu: [
        { id: 'f9', name: 'Ghee Podi Masala Dosa', price: 160, isVeg: true, tag: 'Signature' },
        { id: 'f10', name: 'Grand South Indian Thali', price: 220, isVeg: true, tag: 'Filling' },
        { id: 'f11', name: 'Steamed Button Idlis (4 pcs)', price: 90, isVeg: true, tag: 'Healthy' },
        { id: 'f12', name: 'Filter Coffee Traditional Brass Pot', price: 60, isVeg: true, tag: 'Iconic' }
      ]
    }
  ],

  // 6. Movies & Events Mock Data
  entertainment: [
    {
      id: 'mov-1',
      title: 'Starlight: Beyond Earth (3D IMAX)',
      type: 'movie',
      language: 'English, Hindi, Tamil',
      genre: 'Sci-Fi • Adventure • Action',
      rating: 4.7,
      duration: '2h 45m',
      poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
      showtimes: ['11:30 AM', '02:45 PM', '06:15 PM', '09:45 PM'],
      venue: 'CineGenie IMAX Screen 1',
      silverPrice: 220,
      goldPrice: 340,
      reclinerPrice: 550
    },
    {
      id: 'mov-2',
      title: 'Sunburn Goa Sunset Music Festival',
      type: 'concert',
      language: 'Live Music',
      genre: 'EDM • Cultural • Live DJ',
      rating: 4.9,
      duration: '6 Hours',
      poster: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
      showtimes: ['04:00 PM', '07:30 PM'],
      venue: 'Vagator Beach Arena, Goa',
      silverPrice: 999,
      goldPrice: 1999,
      reclinerPrice: 3499
    },
    {
      id: 'mov-3',
      title: 'Rajasthan Royal Folk Dance & Puppet Gala',
      type: 'event',
      language: 'Hindi, Rajasthani',
      genre: 'Traditional • Cultural • Family',
      rating: 4.8,
      duration: '2 Hours',
      poster: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
      showtimes: ['06:30 PM', '08:45 PM'],
      venue: 'Bagore Ki Haveli Amphitheatre',
      silverPrice: 250,
      goldPrice: 450,
      reclinerPrice: 700
    }
  ],

  // 7. Offline Mesh Network Peers (Trip Connect)
  meshPeers: [
    { id: 'peer-1', name: 'Rahul Sharma', distance: '12m away', signal: 95, status: 'Connected', avatar: '👨‍💼', lastSeen: 'Just now' },
    { id: 'peer-2', name: 'Priya Patel', distance: '28m away', signal: 82, status: 'Connected', avatar: '👩‍⚕️', lastSeen: '1m ago' },
    { id: 'peer-3', name: 'Arjun Das', distance: '45m away', signal: 65, status: 'Connected', avatar: '👨‍🎨', lastSeen: '3m ago' },
    { id: 'peer-4', name: 'Sneha Roy', distance: '85m away', signal: 40, status: 'Connecting...', avatar: '👩‍💻', lastSeen: '5m ago' },
    { id: 'peer-5', name: 'Vikram Singh', distance: '120m away', signal: 25, status: 'Nearby Signal', avatar: '🧗‍♂️', lastSeen: '8m ago' }
  ],

  // 8. Travel Insurance Plans (Trip Protect)
  insurancePlans: [
    {
      id: 'ins-gold',
      name: 'TRIP GENIE TRAVEL PROTECT - GOLD',
      coverageAmount: 500000,
      price: 299,
      status: 'Active',
      policyNo: 'TG-INS-2026-8849102',
      validTill: '31 Dec 2026',
      benefits: [
        'Emergency Medical Hospitalization up to ₹5,00,000',
        'Trip Cancellation & Delay Reimbursement up to ₹25,000',
        'Lost Checked-in Baggage Cover up to ₹30,000',
        '24x7 Emergency Evacuation Assistance',
        'Zero Deductibles on Medical Claims'
      ]
    },
    {
      id: 'ins-platinum',
      name: 'TRIP GENIE SHIELD PLATINUM PLUS',
      coverageAmount: 1500000,
      price: 699,
      status: 'Available',
      policyNo: 'TG-INS-PLAT-9021',
      validTill: '1 Year Full Protection',
      benefits: [
        'High Altitude & Adventure Sports Injury Cover',
        'International Medical Evacuation up to ₹15,00,000',
        'Emergency Cash Advance & Flight Rescheduling',
        'Home Burglary Insurance during Travel',
        'Dedicated VIP Claim Concierge'
      ]
    }
  ],

  // 9. Initial Mock Transactions for TRIP PAY
  initialTransactions: [
    { id: 'TXN-9841', title: 'IndiGo Flight to Goa (DEL → GOI)', category: 'Travel', date: '02 Sep 2026, 09:30 AM', amount: -4299, status: 'Success', icon: '✈️' },
    { id: 'TXN-9840', title: 'Ocean Pearl Luxury Resort Advance', category: 'Hotel', date: '01 Sep 2026, 04:15 PM', amount: -3499, status: 'Success', icon: '🏨' },
    { id: 'TXN-9839', title: 'Coastal Spice Goan Dinner', category: 'Food', date: '01 Sep 2026, 08:45 PM', amount: -620, status: 'Success', icon: '🍜' },
    { id: 'TXN-9838', title: 'Genie Prime Cab Ride (Airport to Hotel)', category: 'Rides', date: '01 Sep 2026, 10:20 AM', amount: -249, status: 'Success', icon: '🚕' },
    { id: 'TXN-9837', title: 'Added to Trip Genie Wallet (UPI)', category: 'Wallet Top-up', date: '30 Aug 2026, 02:00 PM', amount: 15000, status: 'Success', icon: '💳' }
  ],

  // 10. Initial Bookings List
  initialBookings: [
    {
      id: 'TG-BK-7701',
      serviceType: 'Flights',
      title: 'Delhi (DEL) → Goa (GOI)',
      provider: 'IndiGo 6E-2044',
      date: '15 Oct 2026',
      time: '06:30 AM',
      passengers: '2 Adults',
      price: 4299,
      status: 'Confirmed',
      seat: '12A, 12B',
      gate: 'Terminal 3, Gate 14'
    },
    {
      id: 'TG-BK-7702',
      serviceType: 'Hotels',
      title: 'Ocean Pearl Luxury Beach Resort',
      provider: 'Calangute Beach, Goa',
      date: '15 Oct - 19 Oct 2026',
      time: 'Check-in: 02:00 PM',
      passengers: '2 Guests • Deluxe Sea View',
      price: 3499,
      status: 'Confirmed',
      seat: 'Room 304'
    },
    {
      id: 'TG-BK-7703',
      serviceType: 'Rides',
      title: 'Goa Airport (GOI) → Calangute',
      provider: 'Genie Prime Sedan (Maruti Dzire)',
      date: '15 Oct 2026',
      time: '09:30 AM',
      passengers: 'Driver: Ramesh Sharma',
      price: 249,
      status: 'Confirmed',
      seat: 'GA-03-AB-4921'
    }
  ],

  // 11. Emergency Helplines Directory
  emergencyServices: [
    { name: 'National Emergency SOS', number: '112', icon: '🆘', desc: 'Unified All-India Emergency Number' },
    { name: 'Police Helpline', number: '100', icon: '👮‍♂️', desc: 'Immediate Police Assistance' },
    { name: 'Ambulance & Medical', number: '108', icon: '🚑', desc: 'Medical Trauma & Emergency Care' },
    { name: 'Fire & Rescue Service', number: '101', icon: '🚒', desc: 'Fire Brigade & Disaster Management' },
    { name: 'Women Safety Helpline', number: '1091', icon: '🛡️', desc: 'Dedicated 24x7 Women Safety Cell' },
    { name: 'National Tourist Helpline', number: '1363', icon: '🧭', desc: 'Multi-lingual Tourist Assistance' }
  ]
};

// Export to window
window.TRIP_GENIE_DATA = TRIP_GENIE_DATA;
